version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql_test
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=nodeuser
    ports:
      - "3306:3306"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data
volumes:
  data_sql: {}
  redis_data: {}